name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: SonarCloud analyzes
      run: mvn -B sonar:sonar -Dsonar.host.url=$HOST -Dsonar.organization=$ORG -Dsonar.projectKey=$KEY -Dsonar.login=$LOGIN
      env:
          LOGIN: ${{ secrets.sonar_login }}
          HOST: "https://sonarcloud.io"
          ORG: ${{ secrets.sonar_organization }}
          KEY: ${{ secrets.sonar_project_key }}
